import Head from 'next/head'
import { Box, Container } from '@mui/material';
import Navbar from './Navigation'

const Layout: React.FC<{ children?: React.ReactNode }> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          display: 'flex',
          minHeight: '100vh',
          flexDirection: 'row',
          alignItems: 'stretch',
        }}
      >
        <Navbar />
        <Container
          component="main"
          maxWidth={false}
          disableGutters
        >
          {children}
        </Container>
      </Box>
    </>
  )
}
export default Layout;
